GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
[New LWP 671931]
[New LWP 671932]
[New LWP 671933]
[New LWP 671934]
[New LWP 671935]
[New LWP 671965]
[New LWP 671966]
[New LWP 672034]
[New LWP 672036]
[New LWP 672037]
[New LWP 672039]
[New LWP 672040]
[New LWP 672129]
[New LWP 672130]
[New LWP 672131]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f897d2fadff in __GI___wait4 (pid=1787382, stat_loc=0x0, options=0, 
    usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27

Stack backtrace
---------------
    (pid=1787382, stat_loc=0x0, options=0, usage=0x0)
    at ../sysdeps/unix/sysv/linux/wait4.c:27
        resultvar = 18446744073709551104
        sc_cancel_oldtype = 0
#1  0x00007f894c418224 in  ()
    at /usr/lib/python3/dist-packages/cysignals/signals.cpython-38-x86_64-linux-gnu.so
#2  0x00007f894c418366 in  ()
    at /usr/lib/python3/dist-packages/cysignals/signals.cpython-38-x86_64-linux-gnu.so
#3  0x00007f894c41ad5f in  ()
    at /usr/lib/python3/dist-packages/cysignals/signals.cpython-38-x86_64-linux-gnu.so
#4  0x00007f897d25b210 in <signal handler called> ()
    at /lib/x86_64-linux-gnu/libc.so.6
#5  0x00007f8961473192 in sip_api_get_address ()
    at /usr/lib/python3/dist-packages/sip.cpython-38-x86_64-linux-gnu.so
#6  0x00007f89616a5355 in  ()
    at /usr/lib/python3/dist-packages/PyQt5/QtCore.cpython-38-x86_64-linux-gnu.so
#7  0x00007f8961473b60 in  ()
    at /usr/lib/python3/dist-packages/sip.cpython-38-x86_64-linux-gnu.so
#8  0x00007f89616a50a0 in  ()
    at /usr/lib/python3/dist-packages/PyQt5/QtCore.cpython-38-x86_64-linux-gnu.so
#9  0x00000000005c5166 in  ()
#10 0x00000000005f56c7 in PyObject_Call ()
#11 0x0000000000652ca4 in  ()
#12 0x000000000067fe68 in Py_FinalizeEx ()
#13 0x000000000067eabc in Py_Exit ()
#14 0x000000000067eaeb in  ()
#15 0x000000000067ed16 in PyErr_PrintEx ()
#16 0x000000000067ef75 in PyRun_SimpleFileExFlags ()
#17 0x00000000006b7242 in Py_RunMain ()
#18 0x00000000006b75cd in Py_BytesMain ()
#19 0x00007f897d23c0b3 in __libc_start_main (main=
    0x4eec50 <main>, argc=2, argv=0x7ffcb15f8ec8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffcb15f8eb8)
    at ../csu/libc-start.c:308
        result = <optimized out>
        unwind_buf = 
              {cancel_jmp_buf = {{jmp_buf = {7042528, 961609945703799306, 6271328, 140723284315840, 0, 0, -963434309901329910, -987790933726176758}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x2, 0x7ffcb15f8ec8}, data = {prev = 0x0, cleanup = 0x0, canceltype = 2}}}
        not_first_call = <optimized out>
#20 0x00000000005fb18e in _start ()
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


Cython backtrace
----------------
#0  0x00007f897d2fada0 in __GI___wait4 () at /build/glibc-eX1tMB/glibc-2.31/posix/../sysdeps/unix/sysv/linux/wait4.c:27
#1  0x0000000000000000 in ?? ()
#2  0x0000000000000000 in ?? ()
#3  0x0000000000000000 in ?? ()
#4  0x00007f897d2073c0 in __restore_rt ()
#5  0x00007f8961473180 in sip_api_get_address ()
#6  0x0000000000000000 in ?? ()
#7  0x0000000000000000 in ?? ()
#8  0x0000000000000000 in ?? ()
#9  0x0000000000000000 in ?? ()
#10 0x00000000005f54d0 in PyObject_Call ()
#11 0x0000000000000000 in ?? ()
#12 0x000000000067fe20 in Py_FinalizeEx ()
#13 0x000000000067eab0 in Py_Exit ()
#14 0x0000000000000000 in ?? ()
#15 0x000000000067ed00 in PyErr_PrintEx ()
#16 0x000000000067edb0 in PyRun_SimpleFileExFlags ()
#17 0x00000000006b7030 in Py_RunMain ()
#18 0x00000000006b75a0 in Py_BytesMain ()
#19 0x00007f897d23bfc0 in __libc_start_main () at /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308
#20 0x00000000005fb160 in _start ()

[Inferior 1 (process 671915) detached]
27	../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
